<img src="backups/numpy_logo.png" height="10px" alt="NUMPY LOGO" align='left' hspace="10px" >
<h1> Introduction to Numpy </h1>

NumPy is a Python package which stands for ‘Numerical Python’. It is the core library for scientific computing, which contains a powerful n-dimensional array object, provide tools for integrating C, C++ etc. It is also useful in linear algebra, random number capability etc. 

In [16]:
import numpy as np

In [3]:
print (np.__version__)

1.18.1


In [17]:
gpa_list = [9.0,8.8,7.9,8.5]

In [17]:
# appending to the list
gpa_list.append(7)

In [18]:
gpa_list.insert(2, "hello")

In [20]:
gpa_list.pop(2)

'hello'

In [22]:
gpa_list

[9.0, 8.8, 7.9, 8.5, 7, 7]

#### Definition of an Numpy Array
- A NumPy array is a central data structure of the numpy library

#### Properties of an Numpy array
- Array can have only one type of data
- Array size is immutable, it cannot be changed

Above these two properties makes numpy array faster than basic python functionalities

In [4]:
gpa_list = [9.0,8.8,7.9,8.5]

Python list allow to keep multiple datatype in a single list, channging the size of the list but Numpy array dont allow these operations

## Creating a Numpy Arrray

To make a numpy array, you can just use the np.array() function

In [18]:
gpa_array=np.array(gpa_list)

In [6]:
gpa_array

array([9. , 8.8, 7.9, 8.5])

In [9]:
gpa_array.dtype

dtype('float64')

In [28]:
?gpa_array

In [11]:
gpa_array.size

4

In [19]:
gpa_array.ndim

1

In [20]:
gpa_array.itemsize

8

### Creating an array with Zeros

In [22]:
x = np.zeros(100)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [23]:
x.itemsize 

8

#### Few Important Attributes of Numpy Array
- ndim: Gives the dimension of the array, 
- itemsize: Gives the byte size of each element
- dtype: Gives the data type of the elements that are stored in an array
- size: Number of elements in the array.
- shape: Shape of the array

In [27]:
x.nbytes  # size*itemsize

800

In [27]:
%whos

Variable    Type       Data/Info
--------------------------------
gpa_array   ndarray    4: 4 elems, type `float64`, 32 bytes
gpa_list    list       n=6
np          module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
x           ndarray    100: 100 elems, type `float64`, 800 bytes


### Choosing a right datatype can save lots of Memory and makes the code faster

In [5]:
x = np.zeros(100,np.uint16)
print(x)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [30]:
%whos

Variable    Type       Data/Info
--------------------------------
gpa_array   ndarray    4: 4 elems, type `float64`, 32 bytes
gpa_list    list       n=6
np          module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
x           ndarray    100: 100 elems, type `uint16`, 200 bytes


In [6]:
x[0] = 150

In [7]:
print(x[0])

150


In [8]:
x

array([150,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=uint16)

### Scalar and Vector Datatype

In [12]:
type(x)  # Vector/array objects

numpy.ndarray

In [11]:
type(x[0]) # Scalar objects

numpy.uint16

In [13]:
x[1:5]=[120,60,90,200]

In [14]:
x


array([150, 120,  60,  90, 200,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=uint16)

### Datatypes in NUMPY

<a href="https://numpy.org/devdocs/user/basics.types.html">Numpy official Docs Link</a>